export const INIT_APP = 'INIT_APP';
export const FECTH_DETAILS = 'FECTH_DETAILS';
export const FECTH_DETAILS_SUCCESS = 'FECTH_DETAILS_SUCCESS';
export const FECTH_DETAILS_FAILED = 'FECTH_DETAILS_FAILED';
export const UPDATE_WATCHED_STATE = 'UPDATE_WATCHED_STATE';
export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const UPDATE_SELECTED_MOVIE_DETAILS = 'UPDATE_SELECTED_MOVIE_DETAILS';